### ISSUE TITLE
Web page crashes while adding level information 

### ISSUE THREAD

**Issue by darrow97** [Project-Hedron/Issues-and-Tasks#3] opened 2024-04-02 21:08 UTC
It is known that more data for a web page will slow down TTM performance.

While adding level data to classes, the increase in data effects TTM performance to the point of crashing the current web page (and not the site)

Here is the error
![image](https://github.com/Tabletop-Mirror/Issues-and-Tasks/assets/46908712/e888bad3-350f-41e5-97a2-1176e9416773)

Browser: Brave v1.63.161

**Comment by darrow97** [comment] 2024-04-03 19:29
While working with @SirClutch6, we edited the Ranger class with System Monitor (the process and resource monitor for Linux) open to view the Memory usage of the browser. 
We noticed a massive spike (jumping from a few hundred Mbs to 4 Gbs) in browser Memory usage before the web page crash. Our actions on the page included scrolling, removing and adding abilities, and searching for abilities.

**Comment by SirClutch6** [comment] 2024-04-03 19:52
We just recreated the problem, taking screenshots of the System Monitor along the way. We can provide those screenshots if that is helpful. 

Note: This time we closed all other tabs and only had TTM open on Brave. The last memory usage for Brave that we saw on the system monitor was 3.9 GiB right before it crashed.

**Comment by VarunS1997** [comment] 2024-04-10 17:19
It appears this was caused by dynamic preview creation repeatedly processing the same data due to the angular lifecycle. 

Resolved by adding a caching mechanism to compute once and remember the computation. 

It's possible this crash may still happen as it was very difficult to get a comprehensive heap dump for this bug, but I do observe substantially reduced memory usage through this fix.

**Comment by SirClutch6** [comment] 2024-04-11 16:29
I am still getting the same problem. The page seems to last marginally longer before crashing, but it still crashes for me very often, especially when editing the later levels such as 19 and 20. 

Note: I did see memory usage get up to 4.8 GiB a few times before crashing.

**Comment by SirClutch6** [comment] 2024-04-11 21:05
Working a lot better! Memory usage topped out at around 2.2 GiB, but I had no crashes even when making a lot of changes to test it.

**Comment by VarunS1997** [comment] 2024-04-12 00:29
Still pretty heavy 😅 

I'll look into further improvements I can make to reduce the usage even more.

**Comment by VarunS1997** [comment] 2024-05-29 21:04
Closing it for now because the usage is much better now and we can always re-open if it comes up again.

**Closed as completed by VarunS1997** 2024-05-29 21:04 UTC
Labels: bug, P3
