### ISSUE TITLE
Can't Access User Profiles

### ISSUE THREAD

**Issue by VarunS1997** [Project-Hedron/Issues-and-Tasks#146] opened 2024-07-23 20:54 UTC
```
Name of the game:

Bug description:

Steps to reproduce:
Just look at a person's profile and it says it's not gonna let you

Any additional relevant info:

Attach screenshots to the email if you have any relevant captures.

Discord username:
RoleGate username: Southpaw-Senpai
Platform: android
App version: 1.188
```

**Comment by SirClutch6** [comment] 2024-07-24 22:08
Is there any more information on this? I cannot duplicate the bug on the web or android app.

**Comment by VarunS1997** [comment] 2024-07-25 04:47
@SirClutch6 it's just from the trello board. It's totally possible it's not reproducible easily, in which case, we can close it for now since the upcoming migration will make this a moot point anyway.

**Comment by darrow97** [comment] 2024-07-31 19:51
I also cannot reproduce this bug.

Closing the ticket as a result

**Closed as completed by darrow97** 2024-07-31 19:51 UTC
Labels: bug, wontfix, P3, Role Gate
